#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RecycleViewForWork.Resource", IsApplication=true)]

namespace RecycleViewForWork
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050007
			public const int black = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int black_3 = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int blue_verydark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int dark_gray = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int green_light = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int infobar = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int light_gray = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int line = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int red = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int white = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060012
			public const int button_long = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int button_medium = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int button_short = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int button_verylong = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int edittext_medium = 2131099669;
			
			// aapt resource value: 0x7f06001c
			public const int fragment_header_height = 2131099676;
			
			// aapt resource value: 0x7f060016
			public const int icon_margin = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int icon_medium = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int listview_header_height = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int listview_pending_height = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int listview_report_height = 2131099675;
			
			// aapt resource value: 0x7f060007
			public const int margin_beforemaxlong = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int margin_long = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int margin_maxlong = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int margin_medium = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int margin_mostshort = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int margin_prettylong = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int margin_short = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int margin_verylong = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int margin_verymaxlong = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int margin_veryshort = 2131099649;
			
			// aapt resource value: 0x7f06001f
			public const int material_drawer_item_primary_text = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int tab_height = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int tab_height_mini = 2131099678;
			
			// aapt resource value: 0x7f06000f
			public const int text_heading = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int text_large = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int text_largeheading = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int text_medium = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int text_small = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int text_subheading = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int text_verysmall = 2131099658;
			
			// aapt resource value: 0x7f060018
			public const int toolsbar_height = 2131099672;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int baby = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int imvShow = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int lvShow = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int recyclerView = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int txtDes = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int txtTitle = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int listview_row = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int listview_row2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Divider = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
